language: node_js

node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev

after_script:
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always
